FROM jetty:9.3.3
ADD http://10.58.136.166/assets/sapui5/1.32.3/sapui5-1.32.3-sdk-dist.war /opt/jetty-distribution-9.3.3.v20150827/webapps/root.war

# docker build --no-cache=true -t sapui5-sdk:1.32.3 .